# Generated by Django 3.0.3 on 2020-02-13 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('camera', '0001_initial'),
        ('minuterecords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minuterecords',
            name='cam_id',
        ),
        migrations.AddField(
            model_name='minuterecords',
            name='cam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='camera.Camera'),
        ),
        migrations.AddField(
            model_name='minuterecords',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='driver.Driver'),
        ),
    ]
